version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - zip -g deployment_package1.zip lambda_function.py
      - echo "Zipping deployment package for lambda s3..."
      - cd lib
      - zip -r9 ../deployment_package2.zip .
      - cd ..
      - zip -g deployment_package2.zip lambda_function_s3.py
  post_build:
    commands:
      - echo "Uploading Build Package to S3..."
      - aws s3 cp deployment_package1.zip s3://airbnb-s3-booking-records
      - echo "Uploading Build Package 2 to S3..."
      - aws s3 cp deployment_package2.zip s3://airbnb-s3-booking-records
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name airbnb-booking-data-producer-lambda --s3-bucket airbnb-s3-booking-records --s3-key deployment_package1.zip
      - echo "Invoking Lambda function "
      - aws lambda invoke --function-name airbnb-booking-data-producer-lambda --payload '{"key1": "value1","key2": "value2","key3": "value3"}'
      - aws sqs receive-message --queue-url https://sqs.us-east-1.amazonaws.com/590183810146/airbnb-booking-queue > output.json
      - aws events put-events --entries file://output.json
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name airbnb-processed-filtered-bookings --s3-bucket airbnb-s3-booking-records --s3-key deployment_package2.zip
      - echo "Invoking Lambda function "
      - aws lambda invoke --function-name airbnb-processed-filtered-bookings --payload '{"key1": "value1","key2": "value2","key3": "value3"}'
      - echo "Deployment complete!"